# Copyright 2026 IVERI Project
# SPDX-License-Identifier: Apache-2.0

"""License validation and compatibility checker for IVERI CORE data pipeline.

Verifies that dataset licenses are compatible with research and commercial use
cases, and generates Markdown attribution files.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Any, cast

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class LicenseInfo:
    """Attributes defining the permissions of a license."""

    license: str
    research_ok: bool
    commercial_ok: bool
    attribution_required: bool


@dataclass(frozen=True)
class LicenseReport:
    """Report generated by checking multiple datasets."""

    total_checked: int
    valid_for_research: int
    invalid_for_research: int
    attribution_required_list: list[str]
    unknown_licenses: list[str]
    errors: list[str]
    timestamp: str


LICENSE_COMPATIBILITY: dict[str, LicenseInfo] = {
    "MIT": LicenseInfo("MIT", research_ok=True, commercial_ok=True, attribution_required=True),
    "Apache-2.0": LicenseInfo(
        "Apache-2.0", research_ok=True, commercial_ok=True, attribution_required=True
    ),
    "BSD-2-Clause": LicenseInfo(
        "BSD-2-Clause", research_ok=True, commercial_ok=True, attribution_required=True
    ),
    "BSD-3-Clause": LicenseInfo(
        "BSD-3-Clause", research_ok=True, commercial_ok=True, attribution_required=True
    ),
    "ODC-By": LicenseInfo(
        "ODC-By", research_ok=True, commercial_ok=True, attribution_required=True
    ),
    "CC-BY-4.0": LicenseInfo(
        "CC-BY-4.0", research_ok=True, commercial_ok=True, attribution_required=True
    ),
    "CC-BY-SA-3.0": LicenseInfo(
        "CC-BY-SA-3.0", research_ok=True, commercial_ok=True, attribution_required=True
    ),
    "CC-BY-NC-4.0": LicenseInfo(
        "CC-BY-NC-4.0", research_ok=True, commercial_ok=False, attribution_required=True
    ),
    "NVIDIA-Open-Model": LicenseInfo(
        "NVIDIA-Open-Model", research_ok=True, commercial_ok=False, attribution_required=True
    ),
    "PUBLIC": LicenseInfo(
        "PUBLIC", research_ok=True, commercial_ok=True, attribution_required=False
    ),
    "PROPRIETARY": LicenseInfo(
        "PROPRIETARY", research_ok=True, commercial_ok=True, attribution_required=False
    ),
    "various-permissive": LicenseInfo(
        "various-permissive", research_ok=True, commercial_ok=True, attribution_required=True
    ),
    "unknown": LicenseInfo(
        "unknown", research_ok=False, commercial_ok=False, attribution_required=False
    ),
}


class LicenseChecker:
    """Validates license constraints and generates attribution reports."""

    def __init__(self, registry: Any | None = None) -> None:
        self.registry = registry

    def get_license(self, dataset_name: str) -> str:
        """Get the license identifier string for a dataset."""
        if self.registry:
            try:
                return cast(str, self.registry.get(dataset_name).license)
            except KeyError:
                pass
        return "unknown"

    def verify(self, dataset_name: str, use_case: str = "research") -> bool:
        """Verify if a dataset's license is compatible with the use case."""
        lic = self.get_license(dataset_name)
        info = LICENSE_COMPATIBILITY.get(lic, LICENSE_COMPATIBILITY["unknown"])

        if use_case == "research":
            return info.research_ok
        elif use_case == "commercial":
            return info.commercial_ok
        return False

    def check_all(self, dataset_names: list[str], use_case: str = "research") -> LicenseReport:
        """Check licenses for multiple datasets and summarize in a report."""
        total = len(dataset_names)
        valid = 0
        invalid = 0
        attr_list = []
        unknown_list = []
        errors = []

        for name in dataset_names:
            lic = self.get_license(name)
            info = LICENSE_COMPATIBILITY.get(lic, LICENSE_COMPATIBILITY["unknown"])

            if info.license == "unknown":
                unknown_list.append(name)
                errors.append(f"Dataset '{name}' has an unknown license.")
                invalid += 1
                continue

            # Check compatibility
            ok = info.research_ok if use_case == "research" else info.commercial_ok
            if ok:
                valid += 1
                if info.attribution_required:
                    attr_list.append(name)
            else:
                invalid += 1
                errors.append(
                    f"Dataset '{name}' license '{lic}' is incompatible with '{use_case}' use case."
                )

        return LicenseReport(
            total_checked=total,
            valid_for_research=valid,
            invalid_for_research=invalid,
            attribution_required_list=attr_list,
            unknown_licenses=unknown_list,
            errors=errors,
            timestamp=datetime.now().isoformat(),
        )

    def generate_attribution_report(self, datasets: list[str]) -> str:
        """Generate a Markdown document detailing data attributions."""
        lines = [
            "# IVERI CORE — Dataset Attribution Report",
            "",
            f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "This report lists all datasets used, their licenses, and required attributions.",
            "",
            "| Dataset | License | Research OK | Commercial OK | Attribution Required |",
            "|---|---|---|---|---|",
        ]

        for name in sorted(datasets):
            lic = self.get_license(name)
            info = LICENSE_COMPATIBILITY.get(lic, LICENSE_COMPATIBILITY["unknown"])
            lines.append(
                f"| {name} | {info.license} | {'Yes' if info.research_ok else 'No'} | "
                f"{'Yes' if info.commercial_ok else 'No'} | {'Yes' if info.attribution_required else 'No'} |"
            )

        lines.append("")
        lines.append("## Required Attributions")
        lines.append("")

        attr_needed = False
        for name in sorted(datasets):
            lic = self.get_license(name)
            info = LICENSE_COMPATIBILITY.get(lic, LICENSE_COMPATIBILITY["unknown"])
            if info.attribution_required:
                attr_needed = True
                lines.append(f"### {name}")
                lines.append(f"- **License**: {info.license}")
                if self.registry:
                    try:
                        entry = self.registry.get(name)
                        lines.append(f"- **Description**: {entry.description}")
                        if entry.hf_id:
                            lines.append(
                                f"- **Source**: [Hugging Face Hub](https://huggingface.co/datasets/{entry.hf_id})"
                            )
                    except KeyError:
                        pass
                lines.append("")

        if not attr_needed:
            lines.append("No explicit attributions are required for the selected datasets.")

        return "\n".join(lines)
