# Copyright 2026 IVERI Project
# SPDX-License-Identifier: Apache-2.0

"""Interactive inference and generation demo for the IVERI CORE architecture.

Loads saved model checkpoints and generates text using different sampling
strategies (greedy, temperature, top-k, nucleus/top-p).
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import torch
import torch.nn.functional as F

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from configs.base_config import IVERIConfig
from model.iveri_core import IVERIModel


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for generation."""
    parser = argparse.ArgumentParser(
        description="IVERI CORE — Inference & Text Generation Demo",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--checkpoint",
        type=str,
        required=True,
        help="Path to saved model checkpoint (.pt).",
    )
    parser.add_argument(
        "--prompt",
        type=str,
        default="Once upon a time, there was a little",
        help="Input text prompt to seed generation.",
    )
    parser.add_argument(
        "--max-new-bytes",
        type=int,
        default=64,
        help="Maximum number of new bytes/tokens to generate.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.8,
        help="Sampling temperature (higher = more creative/random). 0.0 is greedy.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=50,
        help="Top-k sampling threshold (filter to top K highest probability tokens).",
    )
    parser.add_argument(
        "--top-p",
        type=float,
        default=0.9,
        help="Top-p/nucleus sampling threshold (filter to cumulative probability P).",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        choices=["cpu", "cuda"],
        help="Device to run inference on.",
    )
    return parser.parse_args()


@torch.no_grad()
def generate(
    model: IVERIModel,
    prompt_bytes: bytes,
    max_new_bytes: int,
    temperature: float = 0.8,
    top_k: int = 50,
    top_p: float = 0.9,
    device: torch.device = torch.device("cpu"),
) -> bytes:
    """Generate bytes autoregressively using specified sampling parameters.

    Args:
        model: Loaded model instance.
        prompt_bytes: Seed text encoded as bytes.
        max_new_bytes: Number of tokens/bytes to generate.
        temperature: Temperature value.
        top_k: Top-k value.
        top_p: Top-p value.
        device: Device to run tensors on.

    Returns:
        Generated bytes (excluding the prompt).
    """
    model.eval()
    
    # Convert prompt to tensor of shape (1, S)
    input_ids = torch.tensor(list(prompt_bytes), dtype=torch.long, device=device).unsqueeze(0)
    generated = []

    for _ in range(max_new_bytes):
        # Forward pass to get logits for next token
        outputs = model(input_ids, return_dict=True)
        if isinstance(outputs, dict):
            logits = outputs["logits"][:, -1, :]  # Shape: (1, 256)
        else:
            logits = outputs[:, -1, :]

        # 1. Greedy sampling (temperature = 0)
        if temperature <= 0.0:
            next_token = torch.argmax(logits, dim=-1)
        else:
            # Scale by temperature
            scaled_logits = logits / temperature

            # 2. Top-k filtering
            if top_k > 0:
                indices_to_remove = scaled_logits < torch.topk(scaled_logits, top_k)[0][..., -1, None]
                scaled_logits[indices_to_remove] = -float("Inf")

            # 3. Top-p (nucleus) filtering
            if 0.0 < top_p < 1.0:
                sorted_logits, sorted_indices = torch.sort(scaled_logits, descending=True)
                cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)

                # Remove tokens with cumulative probability above threshold
                sorted_indices_to_remove = cumulative_probs > top_p
                # Keep at least the highest probability token
                sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                sorted_indices_to_remove[..., 0] = False

                indices_to_remove = sorted_indices_to_remove.scatter(1, sorted_indices, sorted_indices_to_remove)
                scaled_logits[indices_to_remove] = -float("Inf")

            # Apply softmax and sample
            probs = F.softmax(scaled_logits, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1).squeeze(-1)

        token_val = next_token.item()
        generated.append(token_val)

        # Append generated token to input sequence for next step
        input_ids = torch.cat([input_ids, next_token.unsqueeze(0)], dim=-1)

    return bytes(generated)


def main() -> None:
    """Main generation script."""
    args = parse_args()

    checkpoint_path = Path(args.checkpoint)
    if not checkpoint_path.exists():
        print(f"Checkpoint file not found: {checkpoint_path}")
        sys.exit(1)

    device = torch.device(args.device)
    if device.type == "cuda" and not torch.cuda.is_available():
        print("CUDA device requested but not available. Falling back to CPU.")
        device = torch.device("cpu")

    print(f"Loading checkpoint from: {checkpoint_path}...")
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)

    # --- Config resolution (priority order) ---
    # 1. config_dict embedded in the checkpoint itself
    # 2. config_snapshot.json sitting next to the checkpoint file
    # 3. Default base config (last resort)
    config_dict = checkpoint.get("config_dict")
    if config_dict is not None:
        config = IVERIConfig.from_dict(config_dict)
        print("Config loaded from checkpoint dict.")
    else:
        snapshot_path = checkpoint_path.parent / "config_snapshot.json"
        if snapshot_path.exists():
            import json
            with open(snapshot_path, "r", encoding="utf-8") as f:
                snapshot = json.load(f)
            # Clamp warmup_steps for inference — validation guard requires warmup < max_steps
            training_cfg = snapshot.get("training", {})
            max_s = training_cfg.get("max_steps", 1000)
            ws = training_cfg.get("warmup_steps", 0)
            if ws >= max_s:
                training_cfg["warmup_steps"] = max(0, max_s - 1)
                snapshot["training"] = training_cfg
            config = IVERIConfig.from_dict(snapshot)
            print(f"Config loaded from: {snapshot_path}")
        else:
            print("Warning: no config found in checkpoint or snapshot. Using default base config.")
            from configs.base_config import get_base_config
            config = get_base_config()


    sd = checkpoint["model_state_dict"]

    # Instantiate model and load state dict
    model = IVERIModel(config)
    model.load_state_dict(sd)
    model.to(device)
    print("Model initialized and parameters loaded successfully.")

    # Encode prompt to bytes
    prompt_bytes = args.prompt.encode("utf-8")
    print(f"Prompt: '{args.prompt}'")
    print(f"Prompt length: {len(prompt_bytes)} bytes")
    print("=" * 70)
    print("Generating...")

    t0 = time.perf_counter()
    new_bytes = generate(
        model=model,
        prompt_bytes=prompt_bytes,
        max_new_bytes=args.max_new_bytes,
        temperature=args.temperature,
        top_k=args.top_k,
        top_p=args.top_p,
        device=device,
    )
    duration = time.perf_counter() - t0

    # Decode output bytes (handling invalid utf-8 sequences gracefully)
    generated_text = new_bytes.decode("utf-8", errors="replace")
    full_text = args.prompt + generated_text

    print(f"\nGenerated Output:\n{generated_text}")
    print("=" * 70)
    print(f"Generation statistics:")
    print(f"  Generated tokens: {args.max_new_bytes} bytes")
    print(f"  Duration:         {duration:.2f} seconds")
    print(f"  Throughput:       {args.max_new_bytes / duration:.2f} bytes/sec")
    print("=" * 70)


if __name__ == "__main__":
    main()
